CREATE TABLE airports (
  AirportID INTEGER NOT NULL AUTO_INCREMENT,
  Name VARCHAR(60) NOT NULL,
  Icao_code VARCHAR(4) NOT NULL,
  Country VARCHAR(3) NOT NULL,
  Region VARCHAR(30) DEFAULT NULL,
  City VARCHAR(30) NOT NULL,
  Type VARCHAR(6) NOT NULL,
  PRIMARY KEY (AirportID)
);